### ISSUE TITLE
Sorteer button toevoegen

### ISSUE THREAD

**Issue by Inevdhoven** [PipHarsveld/Hallo-Strandeiland#108]
Aan de filterbalk een sorteer button toevoegen, zodat er gesorteerd kan worden op nieuwste, meeste trekkers, helpers en delers, op oudste, meeste reacties.

**Comment by PipHarsveld** [comment]
Toegevoegd! Helaas is het niet een werkende sorteerfunctie, want daar is te weinig tijd voor.



![Image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/54938035/759c0f49-0480-48e6-b807-663f3a925337)



![Image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/54938035/dd1ec24c-c620-4cf4-8ec6-a36108ac0919)
