### ISSUE TITLE
Shadow onder de menubalk toevoegen

### ISSUE THREAD

**Issue by PipHarsveld** [PipHarsveld/Hallo-Strandeiland#129]
Als je nu aan het scrollen bent op de pagina en je komt op een wit gedeelte, is er geen onderscheid meer tussen de balk en het element. Door een kleine shadow toe te voegen zou dit probleem opgelost zijn.

![image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/54938035/3de4c916-fa7a-46f2-8023-214bd7f9e1d6)

**Comment by Inevdhoven** [comment]
Shadow is toegevoegd.
