### ISSUE TITLE
Focus op wishcards

### ISSUE THREAD

**Issue by Inevdhoven** [PipHarsveld/Hallo-Strandeiland#130]
Er is nu geen focus op de wishcards op de overview pagina.

<img width="1440" alt="Scherm­afbeelding 2023-06-27 om 14 40 04" src="https://github.com/PipHarsveld/Hallo-Strandeiland/assets/43877754/d0f79459-e7e1-4c5a-8791-3a57a01f5b46">
Je ziet nu niet waar je bent maar je zit wel op een link.

**Comment by PipHarsveld** [comment]
Scherp, had ik niet eerder opgemerkt. Ik heb dit toegevoegd.



![Image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/54938035/924fa771-d98c-4585-b5ab-e48d94edbed6)
