### ISSUE TITLE
Zerostate tekst op overview pagina

### ISSUE THREAD

**Issue by Inevdhoven** [PipHarsveld/Hallo-Strandeiland#133]
Tekst onder de titel wensen aanpassen, zodat het duidelijker is voor mensen die nieuw zijn wat ze kunnen doen op de pagina

**Comment by PipHarsveld** [comment]
De tekst is aangepast, het font is groter en ik heb de tekst afgebroken zodat het er iets beter uit ziet



![Image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/54938035/1cb56fd3-0fd7-4d54-b91d-1449b0338945)
