### ISSUE TITLE
Hamburgermenu een hoge(re) z-index geven

### ISSUE THREAD

**Issue by PipHarsveld** [PipHarsveld/Hallo-Strandeiland#45]
De cards komen boven het hamburgermenu uit, door een z-index op de ul te gooien kan dit opgelost worden

![image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/54938035/1c3c4499-7cc8-4460-874e-574fd3588904)

**Comment by Inevdhoven** [comment]
De bug is opgelost!
