### ISSUE TITLE
[BUGFIX] Width van icon layout in wens kaartjes aanpassen.

### ISSUE THREAD

**Issue by sasjakoning** [PipHarsveld/Hallo-Strandeiland#49]
Deze hebben nu een statische breedte waardoor het niet mooi aligned.

Gebruikt dit voor de width:

    width: calc(100% - 2rem);

Dit is 100% min de padding van de container.

![image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/13648845/f488b0c3-70e6-4c4d-b587-7fd6f55520b0)

**Comment by PipHarsveld** [comment]
Sasja, You are amazing <3
Dit is nu opgelost!
