### ISSUE TITLE
Alvast content ophalen

### ISSUE THREAD

**Issue by Inevdhoven** [PipHarsveld/Hallo-Strandeiland#53]
Content uit Supabase ophalen, zodat we niet alleen maar statische code hebben.

**Comment by PipHarsveld** [comment]
Let op: ook de dummydata van de persoon pagina moet vervangen worden

**Comment by PipHarsveld** [comment]
De content op de overview komt nu uit de database

**Comment by PipHarsveld** [comment]
Alle data die we dynamisch wilde maken komt uit de db! 🎊
