### ISSUE TITLE
Dilemma met masonry

### ISSUE THREAD

**Issue by PipHarsveld** [PipHarsveld/Hallo-Strandeiland#61]
Ik zit een beetje te struggelen met het ontwerp dat ik had gemaakt (zie afb). Ik had namelijk gedacht dat dit wel te doen was in code, maar het blijkt toch lastiger te zijn. Ik heb opties bekeken met een masonry grid, maar dan verschillen alleen de cards in hoogte, de breedte van de kolommen zal gelijk blijven (zie afb). Ik ben dus bang dat dit de enige optie is, maar ik hoor graag wat je hiervan vindt?

Origineel design:
![image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/54938035/f010c4d7-1912-409b-9e61-9333e213309d)

Wat mogelijk is met css masonry:
![image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/54938035/e96bb3ef-f4ab-4629-86b9-f33d34aa058f)

**Comment by PipHarsveld** [comment]
Ik heb het overlegd met Justus tijdens een code review. Het eerste plan is inderdaad heel ingewikkeld dus we kunnen beter gaan voor het onderste design maar dan met verschillende kolom breedtes om toch het speelse effect te creëren. Ben je het daarmee eens?

**Comment by Inevdhoven** [comment]
Ja daar ben ik het mee eens. Misschien is het zelfs wel overzichtelijker en kunnen de cards op deze manier beter weergegeven worden dan in ons eerste idee.
