### ISSUE TITLE
Toegankelijkheid controleren

### ISSUE THREAD

**Issue by PipHarsveld** [PipHarsveld/Hallo-Strandeiland#64]
Door pagina tabben, evt met screenreader testen?

**Comment by Inevdhoven** [comment]
Ik ben even door de website met tab gegaan en daar kwam ik de volgende punten tegen:

- De wishcards hebben geen focus
- Je gaat uit de dialog met tab
- Zoek icoon in de header wordt overgeslagen

**Comment by Inevdhoven** [comment]
Het zoek icoon heb ik al opgelost dit was geen button maar alleen een label. Hier heb ik nu een button van gemaakt.

**Comment by Inevdhoven** [comment]
Dat je uit de dialog gaat met tab, gaan we niet meer kunnen oplossen in de tijd die we nu nog hebben.

**Comment by PipHarsveld** [comment]
Ine heeft nog een contrast check gedaan. Ik heb een screenreader test gedaan en een lighthouse test, de resultaten en verbeteringen staan gedocumenteerd in onze wiki.
