### ISSUE TITLE
Poster maken

### ISSUE THREAD

**Issue by PipHarsveld** [PipHarsveld/Hallo-Strandeiland#66]
Voor de eindpresentatie bij zowel de opdrachtgever als bij de oplevering met 'kraampje' is het handig om een poster te maken in de huisstijl van strandeiland dat kort onze opdracht/user stories uitlegd en verteld hoe we dit hebben opgelost. Op die manier heb je een duidelijke infobron met samenvatting van onze afgelopen 5 weken

**Comment by Inevdhoven** [comment]
De poster is gemaakt, moet alleen nog geprint worden.
