### ISSUE TITLE
Detail wens pagina: nadenken over mensen met lange namen

### ISSUE THREAD

**Issue by PipHarsveld** [PipHarsveld/Hallo-Strandeiland#81]
Feedback van de opdrachtgever: Hoe ziet dit eruit als iemand een hele lange naam heeft? En als iemand geen foto heeft? (of is dit verplicht?)

![image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/54938035/b963479f-c979-4ee7-b205-b7b2cf131880)

**Comment by Inevdhoven** [comment]
We hebben het overlegt en denken dat het slim is om het woord organisatie te vervangen door een icoontje te plaatsen en wanneer de naam te lang wordt komen er puntjes en kun je om de volledige naam te zien de pagina van de persoon bekijken.

**Comment by PipHarsveld** [comment]
Voor het icoontje twijfelen we nog. Eerst dachten we aan een kroontje, maar nu lijkt het op een koningin oid. 
Een ster is ook een optie en is gepaster qua belangrijkheid, maar die gebruiken we al om aan te geven hoe veel menen die wens delen. 

![image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/54938035/b47e6fe9-19e3-4036-8503-e90af52fc731)
