### ISSUE TITLE
Nadenken over breadcrumbs

### ISSUE THREAD

**Issue by PipHarsveld** [PipHarsveld/Hallo-Strandeiland#82]
Feedback opdrachtgever: Hoe ziet dit eruit als een wens meerdere thema's heeft? Het heeft nu ook wat weg van breadcrumbs maar dat is misschien niet de bedoeling

![image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/54938035/eb558a35-f901-4940-80e0-2f6bf3b12826)

**Comment by Inevdhoven** [comment]
Dit is nu als volgt, het is uiteindelijk de bedoeling dat je ook op de thema's kan klikken maar daar hebben we helaas geen tijd meer voor.

![Image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/43877754/5717ab42-bf68-40fc-a51b-30173bc600cc)
