### ISSUE TITLE
Wens insturen formulier: Naam van de button veranderen

### ISSUE THREAD

**Issue by PipHarsveld** [PipHarsveld/Hallo-Strandeiland#86]
Feedback opdrachtgever: De tekst in deze button (in het formulier om een nieuwe wens aan te maken) veranderen van "Deel een wens" naar bijvoorbeeld "Verzenden"

![image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/54938035/468da29b-2e62-4795-954c-938d77da3392)

**Comment by Inevdhoven** [comment]
De naam van de button in nu veranderd naar wens plaatsen.
