### ISSUE TITLE
Max aantal woorden op titel en description toevoegen

### ISSUE THREAD

**Issue by PipHarsveld** [PipHarsveld/Hallo-Strandeiland#88]
Om enorme lappen tekst in een wens of titel te voorkomen, is het handig om een maximale lengte mee te geven. Hieronder staan de waardes die we hebben afgesproken met het andere team om zo ook één lijn te trekken in de gezamenlijke database.

title minlength="3" maxlength="40" & description minlength="3" maxlength="200"

**Comment by Inevdhoven** [comment]
Dit is nu toegevoegd met ook javascript validatie, voor progressive enhancement. :)
