### ISSUE TITLE
Css voor thema filters veranderen naar classes, zodat we dit kunnen hergebruiken op de overview page

### ISSUE THREAD

**Issue by PipHarsveld** [PipHarsveld/Hallo-Strandeiland#91]
Op de overview pagina hebben we een filter voor de thema's, maar elk thema moet nog styling krijgen. Hiervan kan ik de styling van Ine hergebruiken maak ik moet even weten waar ik dat kan vinden

**Comment by PipHarsveld** [comment]
Als we van de themas een partial maken en vervolgens de styling niet specifiek maken maar op classes gooien, is het heel makkelijk te herbruiken.

**Comment by Inevdhoven** [comment]
Ik heb nu een partial aangemaakt en deze staat nu op de main.

**Comment by PipHarsveld** [comment]
Thanks!
