### ISSUE TITLE
Popover balk sticky maken

### ISSUE THREAD

**Issue by PipHarsveld** [PipHarsveld/Hallo-Strandeiland#94]
Ik denk dat het handig is dat we deze bovenste balk sticky maken. Als de gebruiker nu ver naar onder scrollt en dan de popover wil sluiten, moet hij weer helemaal naar boven scrollen voor de button.

![image](https://github.com/PipHarsveld/Hallo-Strandeiland/assets/54938035/d9f6d6d9-2b2f-486e-a56d-5fd03bdae9e8)

**Comment by Inevdhoven** [comment]
Dit is nu gefixt. Nu is de balk met de titel, zoekbalk en button om te sluiten sticky zodat je er altijd bij kan. De button om te sluiten heb ik nu zo gestyled dat deze lijkt zoals in het design.
